openapi: 3.0.0
info:
  version: 1.0.0
  title: Investor System API Docs
  description: This is the documentation of the API for Investor System.
schemes: [http, https]
host: localhost:3007
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

paths:
  $ref: ./paths/index.yaml
# definitions:
  # $ref: ./definitions/index.yaml